server:
  port: 8083
  servlet:
    context-path: /library

web:
  config:
    allowed-origin-urls:
      http://localhost:3000,
      http://localhost:3001,
      http://localhost:3002
    max-age: 3600
